# Simplified GitLab CI configuration
# This version focuses on what actually works with your runners

stages:
  - build
  - test

# Variables available to all jobs
variables:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_TYPE: Release

# Linux build using Docker executor
build:linux:
  stage: build
  image: ubuntu:24.04  # Specify image only for Linux
  tags:
    - linux
  before_script:
    - apt-get update -qq
    - apt-get install -y cmake build-essential git
  script:
    - cmake --version
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - cmake --build . -j
    - ls -la bin/
  artifacts:
    paths:
      - build/bin/
      - data/
    expire_in: 1 week

# Test the Linux build
test:linux:
  stage: test
  image: ubuntu:24.04  # Specify image only for Linux
  tags:
    - linux
  needs: ["build:linux"]
  script:
    - ./build/bin/veyrm_tests
    - ./build/bin/veyrm --help

# Windows build (native runner with PowerShell)
build:windows:
  stage: build
  tags:
    - windows  # Native Windows runner
  script:
    # Check build environment
    - Write-Host "Windows native build starting"
    - |
      try {
        cmake --version
      } catch {
        Write-Host "CMake not installed"
      }
    - |
      try {
        where.exe cl
      } catch {
        Write-Host "MSVC not found, trying MinGW..."
      }
    - |
      try {
        where.exe gcc
      } catch {
        Write-Host "GCC not found"
      }
    # Create build directory
    - |
      if (-not (Test-Path build)) {
        New-Item -ItemType Directory -Path build
      }
    - Set-Location build
    # Try to build with available compiler
    - |
      try {
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      } catch {
        try {
          cmake -G "Visual Studio 17 2022" -A x64 ..
        } catch {
          Write-Host "Failed to configure CMake"
          exit 1
        }
      }
    - cmake --build . --config Release -j
    - Get-ChildItem -Path . -Recurse -Filter "*.exe" -ErrorAction SilentlyContinue
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 week
  allow_failure: true  # Allow failure until build tools are confirmed

# Windows test (native runner with PowerShell)
test:windows:
  stage: test
  tags:
    - windows
  needs: ["build:windows"]
  script:
    - Write-Host "Testing Windows build"
    - |
      if (Test-Path "build\bin\Release\veyrm_tests.exe") {
        & "build\bin\Release\veyrm_tests.exe"
      } elseif (Test-Path "build\bin\veyrm_tests.exe") {
        & "build\bin\veyrm_tests.exe"
      } else {
        Write-Host "Tests not found"
      }
    - |
      if (Test-Path "build\bin\Release\veyrm.exe") {
        & "build\bin\Release\veyrm.exe" --help
      } elseif (Test-Path "build\bin\veyrm.exe") {
        & "build\bin\veyrm.exe" --help
      } else {
        Write-Host "Game executable not found"
      }
  allow_failure: true