# Simplified GitLab CI configuration
# This version focuses on what actually works with your runners

stages:
  - build
  - test

# Default image for jobs that don't specify one
default:
  image: ubuntu:24.04

# Variables available to all jobs
variables:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_TYPE: Release

# Linux build using Docker executor
build:linux:
  stage: build
  tags:
    - linux
  before_script:
    - apt-get update -qq
    - apt-get install -y cmake build-essential git
  script:
    - cmake --version
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - cmake --build . -j
    - ls -la bin/
  artifacts:
    paths:
      - build/bin/
      - data/
    expire_in: 1 week

# Test the Linux build
test:linux:
  stage: test
  tags:
    - linux
  needs: ["build:linux"]
  script:
    - ./build/bin/veyrm_tests
    - ./build/bin/veyrm --help

# Windows build (native runner with shell executor)
build:windows:
  stage: build
  tags:
    - windows  # Native Windows runner
  script:
    # Check build environment
    - echo "Windows native build starting"
    - cmake --version || echo "CMake not installed"
    - where cl 2>nul || echo "MSVC not found, trying MinGW..."
    - where gcc 2>nul || echo "GCC not found"
    # Create build directory
    - if not exist build mkdir build
    - cd build
    # Try to build with available compiler
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. || cmake -G "Visual Studio 17 2022" -A x64 ..
    - cmake --build . --config Release -j
    - dir bin\Release 2>nul || dir bin 2>nul
  artifacts:
    paths:
      - build/bin/
    expire_in: 1 week
  allow_failure: true  # Allow failure until build tools are confirmed

# Windows test (native runner)
test:windows:
  stage: test
  tags:
    - windows
  needs: ["build:windows"]
  script:
    - echo "Testing Windows build"
    - if exist build\bin\Release\veyrm_tests.exe (build\bin\Release\veyrm_tests.exe) else (echo "Tests not found in Release")
    - if exist build\bin\veyrm_tests.exe (build\bin\veyrm_tests.exe) else (echo "Tests not found in bin")
    - if exist build\bin\Release\veyrm.exe (build\bin\Release\veyrm.exe --help) else (echo "Game not found")
  allow_failure: true