# GitLab CI configuration - Linux only (ARM64 and x64)
# Builds only for Linux platforms to optimize CI resources

stages:
  - build
  - test

# Variables available to all jobs
variables:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_TYPE: Release

# Linux x64 build using Docker executor
build:linux:x64:
  stage: build
  image: ubuntu:24.04
  tags:
    - linux
    - x64
  before_script:
    - apt-get update -qq
    - apt-get install -y cmake build-essential git
  script:
    - echo "Building for Linux x64"
    - cmake --version
    - uname -m
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - cmake --build . -j
    - ls -la bin/
  artifacts:
    paths:
      - build/bin/
      - data/
    expire_in: 1 week

# Linux ARM64 build using Docker executor
build:linux:arm64:
  stage: build
  image: ubuntu:24.04
  tags:
    - linux
    - arm64
  before_script:
    - apt-get update -qq
    - apt-get install -y cmake build-essential git
  script:
    - echo "Building for Linux ARM64"
    - cmake --version
    - uname -m
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - cmake --build . -j
    - ls -la bin/
  artifacts:
    paths:
      - build/bin/
      - data/
    expire_in: 1 week

# Test the Linux x64 build
test:linux:x64:
  stage: test
  image: ubuntu:24.04
  tags:
    - linux
    - x64
  needs: ["build:linux:x64"]
  script:
    - echo "Testing Linux x64 build"
    - ./build/bin/veyrm_tests
    - ./build/bin/veyrm --help

# Test the Linux ARM64 build
test:linux:arm64:
  stage: test
  image: ubuntu:24.04
  tags:
    - linux
    - arm64
  needs: ["build:linux:arm64"]
  script:
    - echo "Testing Linux ARM64 build"
    - ./build/bin/veyrm_tests
    - ./build/bin/veyrm --help

# Windows builds disabled - preserved for future reference
# Uncomment these sections if Windows builds are needed later
#
# build:windows:
#   stage: build
#   tags:
#     - windows
#   script:
#     - Write-Host "Windows builds currently disabled"
#   when: manual
#   allow_failure: true
#
# test:windows:
#   stage: test
#   tags:
#     - windows
#   needs: ["build:windows"]
#   script:
#     - Write-Host "Windows tests currently disabled"
#   when: manual
#   allow_failure: true