# Simplified GitLab CI configuration
# This version focuses on what actually works with your runners

stages:
  - build
  - test

# Default image for jobs that don't specify one
default:
  image: ubuntu:24.04

# Variables available to all jobs
variables:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_BUILD_TYPE: Release

# Linux build using Docker executor
build:linux:
  stage: build
  tags:
    - linux
  before_script:
    - apt-get update -qq
    - apt-get install -y cmake build-essential git
  script:
    - cmake --version
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
    - cmake --build . -j
    - ls -la bin/
  artifacts:
    paths:
      - build/bin/
      - data/
    expire_in: 1 week

# Test the Linux build
test:linux:
  stage: test
  tags:
    - linux
  needs: ["build:linux"]
  script:
    - ./build/bin/veyrm_tests
    - ./build/bin/veyrm --help

# Windows build (native runner)
build:windows:
  stage: build
  tags:
    - windows
  script:
    - echo "Windows build"
    - cmake --version || echo "CMake not installed"
  allow_failure: true