# Veyrm Configuration File
# This file contains default settings for the game.
# Command-line arguments will override these settings.

# Version Information
version: "0.0.2"

# Game Settings
game:
  # Starting map type: procedural, dungeon, room, corridor, arena, stress
  default_map: procedural
  
  # Enable debug mode (shows FPS, coordinates, etc.)
  debug_mode: false
  
  # Difficulty settings
  difficulty:
    # Damage multiplier for monsters (1.0 = normal)
    monster_damage_multiplier: 1.0
    # Health multiplier for player (1.0 = normal)
    player_health_multiplier: 1.0
    # Experience gain multiplier (1.0 = normal)
    experience_multiplier: 1.0

# Display Settings
display:
  # Terminal theme: auto, dark, light, high_contrast
  theme: auto
  
  # Show FPS counter
  show_fps: false
  
  # Message log settings
  message_log:
    # Maximum number of messages to keep in history
    max_messages: 100
    # Number of messages visible in the UI
    visible_messages: 5
  
  # UI Layout
  layout:
    # Minimum terminal width
    min_terminal_width: 80
    # Minimum terminal height  
    min_terminal_height: 24

# Map Generation Settings
map_generation:
  # Random seed (empty for random, or specify a number)
  seed: ""
  
  # Procedural dungeon settings
  procedural:
    # Map dimensions (Angband standard: 198x66)
    width: 198
    height: 66
    
    # Room generation
    min_rooms: 9
    max_rooms: 20
    min_room_size: 4
    max_room_size: 20
    
    # Corridor settings
    corridor_style: straight  # straight, l_shaped, winding
    
    # Chance for rooms to be lit (0.0 to 1.0)
    lit_room_chance: 0.95
    
    # Chance for doors between rooms (0.0 to 1.0)
    door_chance: 0.15

# Monster Settings
monsters:
  # Initial spawn settings
  initial_monster_count: 10    # Monsters spawned at map generation
  max_per_level: 30            # Maximum monsters allowed on level
  
  # Dynamic spawning
  spawn_rate: 100              # Turns between spawn attempts
  spawn_outside_fov: true      # Only spawn where player can't see
  min_spawn_distance: 5        # Minimum tiles from player
  
  # Difficulty
  depth_scaling: 0.1           # Difficulty increase per level
  threat_budget: 100           # Total threat points per level
  
  # Spawn preferences
  prefer_rooms: true           # Spawn in rooms vs corridors
  room_spawn_percentage: 0.95  # Percentage of monsters to spawn in rooms (0.0-1.0)
  pack_spawn_chance: 0.2       # Chance of group spawns
  
  # Monster behavior
  behavior:
    # Default aggression radius (tiles)
    aggression_radius: 10
    # Chance monsters will pursue through doors
    door_pursuit_chance: 0.7

# Player Settings
player:
  # Starting stats
  starting_hp: 20
  starting_attack: 5
  starting_defense: 2
  
  # Inventory
  inventory_capacity: 26  # a-z slots
  
  # Vision
  fov_radius: 10

# Paths
paths:
  # Data directory (contains monsters.json, items.json, etc.)
  data_dir: "data"
  
  # Save game directory
  save_dir: "saves"
  
  # Log directory (for debug logs)
  log_dir: "logs"

# Performance Settings
performance:
  # Target FPS (affects game loop timing)
  target_fps: 60
  
  # Enable multithreading for map generation
  multithread_generation: true
  
  # Cache size for FOV calculations
  fov_cache_size: 100

# Development Settings
development:
  # Enable assertions in release builds
  release_assertions: false
  
  # Verbose logging
  verbose_logging: false
  
  # Auto-save interval (seconds, 0 to disable)
  autosave_interval: 300

# Keybindings
# Arrow keys and numpad are always supported for movement
# These are additional key mappings
keybindings:
  # Actions
  wait: "."
  pickup: "g"
  inventory: "i"
  drop: "d"
  use: "a"
  examine: "x"
  
  # System
  quit: "q"
  save: "S"
  help: "?"
  new_game: "N"
  
  # Targeting
  target: "t"
  fire: "f"
  
  # Advanced
  run: "shift"  # Hold shift + direction to run
  search: "s"
  open: "o"
  close: "c"
  
  # Debug (only in debug mode)
  toggle_fov: "ctrl+f"
  reveal_map: "ctrl+r"
  spawn_monster: "ctrl+m"