name: Generate Documentation

on:
  push:
    branches: [main]
    paths:
      - 'include/**'
      - 'src/**'
      - 'Doxyfile'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen Doxyfile